services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: app
    image: ghcr.io/sunmh207/ai-codereview-gitlab:1.3.15
    ports:
      - "5001:5001"
      - "5002:5002"
    volumes:
      - ./conf/prompt_templates.yml:/app/conf/prompt_templates.yml
      - ./data:/app/data
      - ./log:/app/log
    env_file:
      - ./conf/.env
    restart: unless-stopped